// Generated by https://quicktype.io

export interface IPhotos {
    albumId:      number;
    id:           number;
    title:        string;
    url:          string;
    thumbnailUrl: string;
}
